import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCurrentUser } from "../src/hooks/auth/useCurrentUser";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { user: currentUser } = useCurrentUser();

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS JWT Auth</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>

        <p className={styles.description}>
          {currentUser
            ? `Hello ${currentUser.email}`
            : "You are not logged in !"}
        </p>

        <div className={styles.grid}>
          <Link href="/about" className={styles.card}>
            <h2>About Page &rarr;</h2>
          </Link>

          <Link href="/login" className={styles.card}>
            <h2>Login Page &rarr;</h2>
          </Link>

          <Link href="/profile" className={styles.card}>
            <h2>Profile Page &rarr;</h2>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
      Powered by {"ajay shanker"}
      </footer>
    </div>
  );
}
